# Cloudflare Worker 配置文件

name = "wechat-bot"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
name = "wechat-customer-service"
# 微信企业号配置
WECHAT_CORP_ID="ww4bc0b35cb610fff6"
WECHAT_KF_SECRET="ww4bc0b35cb610fff6"
WECHAT_KF_TOKEN="ww4bc0b35cb610fff6"
WECHAT_KF_ENCODING_AES_KEY="ww4bc0b35cb610fff6"

# 加密服务配置（由于 CF Worker CRYPTO 兼容性问题，需要单独部署）
CRYPTO_SERVICE_URL="ww4bc0b35cb610fff6"

# OpenAI API 配置
OPENAI_API_KEY="hfRdIVPmYGssbpBKLuyp-grRLNFU5RmAughD_Qm3IAXPxcaZeoVwPCipJ_FmgQKU7zhTsZENQOxnRLxfUoImhg"
OPENAI_BASE_URL="https://api.modelarts-maas.com"
OPENAI_MODEL="dp-r3"
OPENAI_TIMEOUT=30000
# OPENAI_ORGANIZATION=org-your-org-id
# OPENAI_PROJECT=proj-your-project-id

# 系统提示词配置
SYSTEM_PROMPT="your are helpful assistant, reply in chinese, and reply in plain text format, text length should be less than 10240 characters" 


# KV存储配置（用于持久化对话历史）
[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "9054c6b5f9024ea7a694066623be7996"
preview_id = ""

# KV存储配置（用于消息处理状态跟踪）
[[kv_namespaces]]
binding = "MESSAGE_TRACKER"
id = "0b5d2c8cde2b42268cd17eb492b34bd3"
preview_id = ""